#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/garbage.h"
#include "images/shallowsleep.h"

extern player p1;
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  *((volatile unsigned char *)(&REG_DISPCNT)) = MODE3;
  *((volatile unsigned char *)(&REG_DISPCNT) + 1) = 0x04;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  enum gba_state prevState = START;
  drawImageDMA(0,0,240,160,shallowsleep);
  player p1 = {(WIDTH / 2 + 4), (HEIGHT / 2 + 3), 4, 3, GREEN};
  struct oldPos oldPos;
  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        if (prevState != START) {
            drawImageDMA(0,0,240,160,shallowsleep);
            prevState = START;
        }
        waitForVBlank();
        drawCenteredString(60,160,70,140,"shallowsleep",BLACK);
        if (KEY_JUST_PRESSED(BUTTON_START,currentButtons,previousButtons)) {
          state = PLAY;
        }
        break;
      case PLAY:
        if (prevState != PLAY) {
            drawPlay();
            prevState = PLAY;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT,BUTTONS,previousButtons)) {
            p1.x = (WIDTH / 2 + 4);
            p1.y = (HEIGHT / 2 + 3);
            prevState = PLAY;
            state = START;
        }
          player *p1p = &p1;
          oldPos = PlayState(p1p);
          waitForVBlank();
          drawRectDMA(p1p->y,p1p->x,p1p->w,p1p->h,p1p->playerColor);
          drawRectDMA(oldPos.oldy,oldPos.oldx,oldPos.oldw,oldPos.oldh,GRAY);
        
        
        break;
      case WIN:

        // state = ?
        break;
      case LOSE:

        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
